services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - storage:/storage
    environment:
      - PORT=8080
    expose:
      - "8080"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  storage:
